# Generated by Django 5.1.5 on 2025-02-26 11:40

import django.db.models.deletion
import django_jalali.db.models
import iranian_cities.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_module', '0008_employer_county_employer_district_employer_province'),
        ('home_module', '000X_add_tehran_districts'),
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
        ('jobAndCompanyActivity_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='برای مثال 4', verbose_name='روز')),
                ('price', models.IntegerField(help_text='این قیمت کل هست -مثلا برای 7 روز کلا 7000 - قیمت ها به تومان است', verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'زمان نمایش آگهی',
                'verbose_name_plural': 'زمان نمایش آگهی ها',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='مهارت های کارجو')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نوع اشتراک')),
                ('price', models.IntegerField(default=0, help_text='قیمت ها به تومان است - برای رایگان بودن تعرفه این بخش را نادیده بگیرید', verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'تعرفه',
                'verbose_name_plural': 'تعرفه ها',
            },
        ),
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertise_code', models.CharField(db_index=True, help_text='بعد از ثبت مقدار دهی می شود', max_length=220, unique=True, verbose_name='کدآگهی')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان آگهی')),
                ('description_position', models.TextField(verbose_name='موقعیت شغلی')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=120, verbose_name='جنسیت')),
                ('soldier_status', models.CharField(choices=[('پایان خدمت', 'پایان خدمت'), ('معافیت دائم', 'معافیت دائم'), ('معافیت تحصیلی', 'معافیت تحصیلی')], max_length=120, verbose_name='وضعیت سربازی')),
                ('degree', models.CharField(choices=[('مهم نیست', 'مهم نیست'), ('زیر دیپلم', 'زیر دیپلم'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا')], max_length=120, verbose_name='حداقل مدرک تحصیلی')),
                ('type_of_cooperation', models.CharField(choices=[('مهم نیست', 'مهم نیست'), ('کمتر از 3 سال', 'کمتر از 3 سال'), ('3 تا 6 سال', '3 تا 6 سال'), ('بیشتر از 6 سال', 'بیشتر از 6 سال')], max_length=220, verbose_name='سابقه کار مرتبط')),
                ('salary', models.CharField(help_text='درصورت خالی گذاشتن ای بخش مبلغ دستمزد توافقی می شود', max_length=220, verbose_name='حداقل دستمزد')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, help_text='بعد از ثبت مقدار دهی می شود', null=True, verbose_name='تاریخ ثبت')),
                ('expire_date', django_jalali.db.models.jDateTimeField(blank=True, help_text='به صورت خودکار محاسبه می شود', null=True, verbose_name='تاریخ انقضا')),
                ('total_price', models.IntegerField(default=0, help_text='به صورت خودکار محاسبه می شود', verbose_name='جمع کل')),
                ('pay_status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('check_by_admin', models.BooleanField(default=False, verbose_name=' مشاهده  شده توسط ادمین')),
                ('is_show', models.BooleanField(default=False, verbose_name='نمایش داده شود / نشود')),
                ('status', models.CharField(choices=[('unpaid', 'در انتظار پرداخت'), ('pending', 'درحال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='unpaid', max_length=220, verbose_name='وضعیت')),
                ('job_type', models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('دورکاری', 'دورکاری'), ('کارآموزی', 'کارآموزی')], max_length=220, verbose_name='نوع شغل')),
                ('county', iranian_cities.fields.CountyField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.county', verbose_name='نام شهرستان')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_module.tehrandistrict', verbose_name='نام منطقه')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='account_module.employer', verbose_name='کارفرما')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='jobAndCompanyActivity_module.job', verbose_name='شغل')),
                ('province', iranian_cities.fields.ProvinceField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province', verbose_name='نام استان')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisement_module.duration', verbose_name='زمان نمایش')),
                ('skills', models.ManyToManyField(blank=True, null=True, related_name='advertisements', to='advertisement_module.skill', verbose_name='مهارت های کارجو')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='advertisement_module.subscription', verbose_name='نوع اشتراک')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
            },
        ),
        migrations.CreateModel(
            name='ReportAdvertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('image', models.ImageField(blank=True, help_text='در صورت وجود عکس آپلود کنید در غیر این صورت نادیده بگیرید', null=True, upload_to='images/report', verbose_name='عکس')),
                ('status', models.CharField(choices=[('0', 'درحال بررسی'), ('1', 'تایید شده'), ('2', 'رد شده')], default='0', max_length=220, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, help_text='بعد از ثبت مقدار دهی می شود', null=True, verbose_name='تاریخ ثبت')),
                ('advertisment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='advertisement_module.advertisment', verbose_name='آگهی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش ها',
            },
        ),
    ]
