# Generated by Django 5.1.5 on 2025-03-08 14:19

import django.db.models.deletion
import django_jalali.db.models
import iranian_cities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDisplayDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(help_text='برای مثال 4', verbose_name='روز')),
                ('price', models.IntegerField(help_text='این قیمت کل است - مثلاً برای 7 روز، کل 7000 تومان', verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'زمان نمایش آگهی',
                'verbose_name_plural': 'زمان نمایش آگهی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementJobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, help_text='بعد از ثبت مقداردهی می\u200cشود', null=True, verbose_name='تاریخ ثبت')),
                ('expire_date', django_jalali.db.models.jDateTimeField(blank=True, help_text='به\u200cصورت خودکار محاسبه می\u200cشود', null=True, verbose_name='تاریخ انقضا')),
                ('pay_status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('status', models.CharField(choices=[('unpaid', 'در انتظار پرداخت'), ('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='unpaid', max_length=220, verbose_name='وضعیت')),
                ('total_price', models.IntegerField(default=0, help_text='به صورت خودکار محاسبه می\u200cشود', verbose_name='جمع کل')),
                ('is_show', models.BooleanField(default=False, verbose_name='نمایش داده شود / نشود')),
                ('advertise_code', models.CharField(db_index=True, help_text='بعد از ثبت مقداردهی می\u200cشود', max_length=220, unique=True, verbose_name='کدآگهی')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=120, verbose_name='جنسیت')),
                ('age', models.SmallIntegerField(verbose_name='سن')),
                ('married_status', models.CharField(choices=[('متاهل', 'متاهل'), ('مجرد', 'مجرد')], max_length=120, verbose_name='وضعیت تاهل')),
                ('children_number', models.SmallIntegerField(default=0, help_text='در صورت نداشتن فرزند این بخش را نادیده بگیرید', verbose_name='تعداد فرزند')),
                ('soldier_status', models.CharField(blank=True, choices=[('پایان خدمت', 'پایان خدمت'), ('معافیت دائم', 'معافیت دائم'), ('معافیت تحصیلی', 'معافیت تحصیلی')], max_length=120, null=True, verbose_name='وضعیت سربازی')),
                ('field_study', models.CharField(max_length=220, verbose_name='رشته تحصیلی')),
                ('degree', models.CharField(choices=[('زیر دیپلم', 'زیر دیپلم'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا')], max_length=120, verbose_name='مدرک تحصیلی')),
                ('insurance', models.CharField(choices=[('سابقه ندارم', 'سابقه ندارم'), ('کمتر از 3 سال', 'کمتر از 3 سال'), ('3 تا 6 سال', '3 تا 6 سال'), ('بیشتر از 6 سال', 'بیشتر از 6 سال')], max_length=220, verbose_name='سابقه بیمه')),
                ('salary', models.CharField(blank=True, help_text='در صورت خالی گذاشتن، مبلغ دستمزد توافقی می\u200cشود', max_length=220, null=True, verbose_name='حقوق مورد نظر')),
                ('check_by_admin', models.BooleanField(default=False, verbose_name='مشاهده شده توسط ادمین')),
                ('job_type', models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('دورکاری', 'دورکاری'), ('کارآموزی', 'کارآموزی')], max_length=220, verbose_name='نوع کار موردتقاضا')),
                ('history_injury', models.CharField(blank=True, help_text='در صورت وجود، توضیح دهید؛ در غیر این صورت نادیده بگیرید', max_length=220, null=True, verbose_name='سابقه آسیب شغلی')),
                ('description', models.TextField(blank=True, help_text='این فیلد اختیاری است', null=True, verbose_name='توضیحات')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'آگهی متقاضی کار',
                'verbose_name_plural': 'آگهی\u200cهای متقاضیان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=220, verbose_name='نام مکان')),
                ('job', models.CharField(max_length=220, verbose_name='شغل شما')),
                ('duration', models.SmallIntegerField(help_text='بر اساس ماه', verbose_name='مدت زمان')),
            ],
            options={
                'verbose_name': 'سابقه کار',
                'verbose_name_plural': 'سوابق',
            },
        ),
        migrations.CreateModel(
            name='ReportAdvertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('image', models.ImageField(blank=True, help_text='در صورت وجود عکس، آپلود کنید؛ در غیر این صورت نادیده بگیرید', null=True, upload_to='images/report', verbose_name='عکس')),
                ('status', models.CharField(choices=[('0', 'در حال بررسی'), ('1', 'تایید شده'), ('2', 'رد شده')], default='0', max_length=220, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, help_text='بعد از ثبت مقداردهی می\u200cشود', null=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='مهارت\u200cهای کارجو')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نوع اشتراک')),
                ('price', models.IntegerField(default=0, help_text='قیمت\u200cها به تومان است - برای رایگان بودن، این بخش را نادیده بگیرید', verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'تعرفه',
                'verbose_name_plural': 'تعرفه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, help_text='بعد از ثبت مقداردهی می\u200cشود', null=True, verbose_name='تاریخ ثبت')),
                ('expire_date', django_jalali.db.models.jDateTimeField(blank=True, help_text='به\u200cصورت خودکار محاسبه می\u200cشود', null=True, verbose_name='تاریخ انقضا')),
                ('pay_status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('status', models.CharField(choices=[('unpaid', 'در انتظار پرداخت'), ('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='unpaid', max_length=220, verbose_name='وضعیت')),
                ('total_price', models.IntegerField(default=0, help_text='به صورت خودکار محاسبه می\u200cشود', verbose_name='جمع کل')),
                ('is_show', models.BooleanField(default=False, verbose_name='نمایش داده شود / نشود')),
                ('advertise_code', models.CharField(db_index=True, help_text='بعد از ثبت مقداردهی می\u200cشود', max_length=220, unique=True, verbose_name='کدآگهی')),
                ('title', models.CharField(max_length=220, verbose_name='عنوان آگهی')),
                ('description_position', models.TextField(verbose_name='موقعیت شغلی')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=120, verbose_name='جنسیت')),
                ('soldier_status', models.CharField(choices=[('پایان خدمت', 'پایان خدمت'), ('معافیت دائم', 'معافیت دائم'), ('معافیت تحصیلی', 'معافیت تحصیلی')], max_length=120, verbose_name='وضعیت سربازی')),
                ('degree', models.CharField(choices=[('مهم نیست', 'مهم نیست'), ('زیر دیپلم', 'زیر دیپلم'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا')], max_length=120, verbose_name='حداقل مدرک تحصیلی')),
                ('type_of_cooperation', models.CharField(choices=[('مهم نیست', 'مهم نیست'), ('کمتر از 3 سال', 'کمتر از 3 سال'), ('3 تا 6 سال', '3 تا 6 سال'), ('بیشتر از 6 سال', 'بیشتر از 6 سال')], max_length=220, verbose_name='سابقه کار مرتبط')),
                ('salary', models.CharField(blank=True, help_text='درصورت خالی گذاشتن این بخش، مبلغ دستمزد توافقی می\u200cشود', max_length=220, null=True, verbose_name='حداقل دستمزد')),
                ('check_by_admin', models.BooleanField(default=False, verbose_name='مشاهده شده توسط ادمین')),
                ('job_type', models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('دورکاری', 'دورکاری'), ('کارآموزی', 'کارآموزی')], max_length=220, verbose_name='نوع شغل')),
                ('county', iranian_cities.fields.CountyField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.county', verbose_name='نام شهرستان')),
            ],
            options={
                'verbose_name': 'آگهی کارفرما',
                'verbose_name_plural': 'آگهی کارفرمایان',
                'ordering': ['-created_at'],
            },
        ),
    ]
