# Generated by Django 5.1.5 on 2025-02-26 11:41

from django.db import migrations

def add_default_subscription(apps,schema_editor):
    Subscription = apps.get_model('advertisement_module','Subscription')
    Subscription.objects.bulk_create([
        Subscription(name = 'نردبان',price = 0),
        Subscription(name = 'عادی',price = 0),
        Subscription(name = 'ویژه',price = 0),
        Subscription(name = 'فوری',price = 0),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_subscription),
    ]
