# Generated by Django 5.1.5 on 2025-03-08 14:19

import django.db.models.deletion
import iranian_cities.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_module', '0002_initial'),
        ('advertisement_module', '0001_initial'),
        ('home_module', '0001_initial'),
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
        ('jobAndCompanyActivity_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_module.tehrandistrict', verbose_name='نام منطقه'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisement_module.addisplayduration', verbose_name='زمان نمایش'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='account_module.employer', verbose_name='کارفرما'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='jobAndCompanyActivity_module.job', verbose_name='شغل'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='province',
            field=iranian_cities.fields.ProvinceField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province', verbose_name='نام استان'),
        ),
        migrations.AddField(
            model_name='advertisementjobseeker',
            name='county',
            field=iranian_cities.fields.CountyField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.county', verbose_name='نام شهرستان'),
        ),
        migrations.AddField(
            model_name='advertisementjobseeker',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_module.tehrandistrict', verbose_name='نام منطقه'),
        ),
        migrations.AddField(
            model_name='advertisementjobseeker',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements_jobSeeker', to='advertisement_module.addisplayduration', verbose_name='زمان نمایش'),
        ),
        migrations.AddField(
            model_name='advertisementjobseeker',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements_jobSeeker', to='jobAndCompanyActivity_module.job', verbose_name='شغل'),
        ),
        migrations.AddField(
            model_name='advertisementjobseeker',
            name='jobSeeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='account_module.jobseeker', verbose_name='کارجو'),
        ),
        migrations.AddField(
            model_name='advertisementjobseeker',
            name='province',
            field=iranian_cities.fields.ProvinceField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province', verbose_name='نام استان'),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_histories', to='account_module.jobseeker', verbose_name='کارجو'),
        ),
        migrations.AddField(
            model_name='reportadvertisment',
            name='advertisment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='advertisement_module.advertisement', verbose_name='آگهی کارفرما'),
        ),
        migrations.AddField(
            model_name='reportadvertisment',
            name='advertisment_jobSeeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='advertisement_module.advertisementjobseeker', verbose_name='آگهی کارجو'),
        ),
        migrations.AddField(
            model_name='reportadvertisment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='advertisementjobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='advertisements_jobSeeker', to='advertisement_module.skill', verbose_name='مهارت\u200cهای شما'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='advertisements', to='advertisement_module.skill', verbose_name='مهارت\u200cهای کارجو'),
        ),
        migrations.AddField(
            model_name='advertisementjobseeker',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements_jobSeeker', to='advertisement_module.subscription', verbose_name='نوع اشتراک'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='advertisement_module.subscription', verbose_name='نوع اشتراک'),
        ),
    ]
