# Generated by Django 5.1.5 on 2025-02-17 15:54

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0001_initial'),
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='county',
            field=iranian_cities.fields.CountyField(default='', on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.county', verbose_name='نام شهرستان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisment',
            name='province',
            field=iranian_cities.fields.ProvinceField(default='', on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province', verbose_name='نام استان'),
            preserve_default=False,
        ),
    ]
