# Generated by Django 5.1.5 on 2025-02-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0002_auto_20250226_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisment',
            options={'ordering': ['-created_at'], 'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی ها'},
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='salary',
            field=models.CharField(blank=True, help_text='درصورت خالی گذاشتن ای بخش مبلغ دستمزد توافقی می شود', max_length=220, null=True, verbose_name='حداقل دستمزد'),
        ),
    ]
