# Generated by Django 5.1.5 on 2025-02-17 16:21

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0002_advertisment_county_advertisment_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, help_text='بعد از ثبت مقدار دهی می شود', null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
