# Generated by Django 5.1.5 on 2025-03-01 17:25

import django.db.models.deletion
import django_jalali.db.models
import iranian_cities.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_employer_county_employer_district_employer_province'),
        ('advertisement_module', '0003_alter_advertisment_options_alter_advertisment_salary'),
        ('home_module', '000X_add_tehran_districts'),
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
        ('jobAndCompanyActivity_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisment',
            options={'ordering': ['-created_at'], 'verbose_name': 'آگهی کارفرما', 'verbose_name_plural': 'اگهی کارفرمایان'},
        ),
        migrations.CreateModel(
            name='AdvertismentJobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertise_code', models.CharField(db_index=True, help_text='بعد از ثبت مقدار دهی می شود', max_length=220, unique=True, verbose_name='کدآگهی')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=120, verbose_name='جنسیت')),
                ('age', models.SmallIntegerField(verbose_name='سن')),
                ('married_status', models.CharField(choices=[('متاهل', 'متاهل'), ('مجرد', 'مجرد')], max_length=120, verbose_name='وضعیت تاهل')),
                ('children_number', models.SmallIntegerField(default=0, help_text='درصورت نداشتن فرزند این بخش را نادیده بگیرید', verbose_name='تعداد فرزند')),
                ('soldier_status', models.CharField(blank=True, choices=[('پایان خدمت', 'پایان خدمت'), ('معافیت دائم', 'معافیت دائم'), ('معافیت تحصیلی', 'معافیت تحصیلی')], max_length=120, null=True, verbose_name='وضعیت سربازی')),
                ('field_study', models.CharField(max_length=220, verbose_name='رشته تحصیلی')),
                ('degree', models.CharField(choices=[('زیر دیپلم', 'زیر دیپلم'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا')], max_length=120, verbose_name='مدرک تحصیلی')),
                ('type_of_cooperation', models.CharField(choices=[('سابقه ندارم', 'سابقه ندارم'), ('کمتر از 3 سال', 'کمتر از 3 سال'), ('3 تا 6 سال', '3 تا 6 سال'), ('بیشتر از 6 سال', 'بیشتر از 6 سال')], max_length=220, verbose_name='سابقه کار مرتبط')),
                ('salary', models.CharField(blank=True, help_text='درصورت خالی گذاشتن ای بخش مبلغ دستمزد توافقی می شود', max_length=220, null=True, verbose_name='حقوق مورد نظر')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, help_text='بعد از ثبت مقدار دهی می شود', null=True, verbose_name='تاریخ ثبت')),
                ('expire_date', django_jalali.db.models.jDateTimeField(blank=True, help_text='به صورت خودکار محاسبه می شود', null=True, verbose_name='تاریخ انقضا')),
                ('total_price', models.IntegerField(default=0, help_text='به صورت خودکار محاسبه می شود', verbose_name='جمع کل')),
                ('pay_status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('is_show', models.BooleanField(default=False, verbose_name='نمایش داده شود / نشود')),
                ('status', models.CharField(choices=[('unpaid', 'در انتظار پرداخت'), ('pending', 'درحال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='unpaid', max_length=220, verbose_name='وضعیت')),
                ('job_type', models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('دورکاری', 'دورکاری'), ('کارآموزی', 'کارآموزی')], max_length=220, verbose_name='نوع کار موردتقاضا')),
                ('history_injury', models.CharField(blank=True, help_text='درصورت وجود موردی توضیح دهید در غیر این صورت نادیده بگیرید', max_length=220, null=True, verbose_name='سابقه آسیب شغلی')),
                ('description', models.TextField(blank=True, help_text='این فیلد اختیاری است', null=True, verbose_name='توضیحات')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('county', iranian_cities.fields.CountyField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.county', verbose_name='نام شهرستان')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_module.tehrandistrict', verbose_name='نام منطقه')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements_jobSeeker', to='advertisement_module.duration', verbose_name='زمان نمایش')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements_jobSeeker', to='jobAndCompanyActivity_module.job', verbose_name='شغل')),
                ('jobSeeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='account_module.employer', verbose_name='کارجو')),
                ('province', iranian_cities.fields.ProvinceField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province', verbose_name='نام استان')),
                ('skills', models.ManyToManyField(blank=True, null=True, related_name='advertisements_jobSeeker', to='advertisement_module.skill', verbose_name='مهارت های شما')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements_jobSeeker', to='advertisement_module.subscription', verbose_name='نوع اشتراک')),
            ],
            options={
                'verbose_name': 'آگهی متقاضی کار',
                'verbose_name_plural': 'آگهی های متقاضیان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAdvertismentJobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('image', models.ImageField(blank=True, help_text='در صورت وجود عکس آپلود کنید در غیر این صورت نادیده بگیرید', null=True, upload_to='images/report', verbose_name='عکس')),
                ('status', models.CharField(choices=[('0', 'درحال بررسی'), ('1', 'تایید شده'), ('2', 'رد شده')], default='0', max_length=220, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, help_text='بعد از ثبت مقدار دهی می شود', null=True, verbose_name='تاریخ ثبت')),
                ('advertisment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='advertisement_module.advertismentjobseeker', verbose_name='آگهی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش ها',
            },
        ),
    ]
