# Generated by Django 5.1.5 on 2025-02-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0004_alter_advertisment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='status',
            field=models.CharField(choices=[('0', 'در انتظار پرداخت'), ('1', 'درحال بررسی'), ('2', 'تایید شده'), ('3', 'رد شده')], default=0, max_length=220, verbose_name='وضعیت'),
        ),
    ]
