# Generated by Django 5.1.5 on 2025-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0004_alter_advertisment_options_advertismentjobseeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertismentjobseeker',
            name='type_of_cooperation',
            field=models.CharField(choices=[('سابقه ندارم', 'سابقه ندارم'), ('کمتر از 3 سال', 'کمتر از 3 سال'), ('3 تا 6 سال', '3 تا 6 سال'), ('بیشتر از 6 سال', 'بیشتر از 6 سال')], max_length=220, verbose_name='سابقه بیمه'),
        ),
    ]
