# Generated by Django 5.1.5 on 2025-02-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0005_alter_advertisment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'در انتظار پرداخت'), ('pending', 'درحال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default=0, max_length=220, verbose_name='وضعیت'),
        ),
    ]
