# Generated by Django 5.1.5 on 2025-03-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_employer_county_employer_district_employer_province'),
        ('advertisement_module', '0005_alter_advertismentjobseeker_type_of_cooperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=220, verbose_name='نام مکان')),
                ('job', models.CharField(max_length=220, verbose_name='شغل شما')),
                ('duration', models.CharField(help_text='براساس ماه', max_length=120, verbose_name='مدت زمان')),
                ('jobSeeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='account_module.jobseeker', verbose_name='کارجو')),
            ],
        ),
    ]
