# Generated by Django 5.1.5 on 2025-03-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0006_insurance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'سابقه کار', 'verbose_name_plural': 'سوابق'},
        ),
    ]
