# Generated by Django 5.1.5 on 2025-02-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0007_alter_advertisment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisment',
            old_name='subscribe',
            new_name='Subscription',
        ),
    ]
