# Generated by Django 5.1.5 on 2025-03-02 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0008_rename_type_of_cooperation_advertismentjobseeker_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportadvertisment',
            name='advertisment_jobSeeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='advertisement_module.advertismentjobseeker', verbose_name='آگهی کارجو'),
        ),
        migrations.AlterField(
            model_name='reportadvertisment',
            name='advertisment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='advertisement_module.advertisment', verbose_name='آگهی کارفرما'),
        ),
        migrations.DeleteModel(
            name='ReportAdvertismentJobSeeker',
        ),
    ]
