# Generated by Django 5.1.5 on 2025-02-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0008_rename_subscribe_advertisment_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisment',
            old_name='Subscription',
            new_name='subscription',
        ),
    ]
