# Generated by Django 5.1.5 on 2025-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0009_rename_subscription_advertisment_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='job_type',
            field=models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('دورکاری', 'دورکاری'), ('کارآموزی', 'کارآموزی')], default='', max_length=220, verbose_name='نوع شغل'),
            preserve_default=False,
        ),
    ]
