# Generated by Django 5.1.5 on 2025-03-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0009_reportadvertisment_advertisment_jobseeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='duration',
            field=models.SmallIntegerField(help_text='براساس ماه', verbose_name='مدت زمان'),
        ),
    ]
