# Generated by Django 5.1.5 on 2025-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0010_advertisment_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='advertisements', to='advertisement_module.skill', verbose_name='مهارت های کارجو'),
        ),
    ]
