# Generated by Django 5.1.5 on 2025-03-03 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_alter_jobseeker_user'),
        ('advertisement_module', '0010_alter_jobhistory_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertismentjobseeker',
            name='jobSeeker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='account_module.jobseeker', verbose_name='کارجو'),
        ),
    ]
