# Generated by Django 5.1.5 on 2025-02-21 16:23

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0013_alter_advertisment_district'),
        ('jobAndCompanyActivity_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobAndCompanyActivity_module.job', verbose_name='شغل کارجو'),
        ),
        migrations.CreateModel(
            name='ReportAdvertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, help_text='بعد از ثبت مقدار دهی می شود', null=True, verbose_name='تاریخ ثبت')),
                ('advertisment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='advertisement_module.advertisment', verbose_name='آگهی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
