# Generated by Django 5.1.5 on 2025-02-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0014_advertisment_job_reportadvertisment'),
        ('jobAndCompanyActivity_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobAndCompanyActivity_module.job', verbose_name='شغل کارجو'),
        ),
    ]
