# Generated by Django 5.1.5 on 2025-02-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0015_alter_advertisment_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='job',
        ),
    ]
