# Generated by Django 5.1.5 on 2025-02-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0016_remove_advertisment_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisment',
            old_name='category',
            new_name='job',
        ),
    ]
