# Generated by Django 5.1.5 on 2025-02-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0018_alter_advertisment_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportadvertisment',
            options={'verbose_name': 'گزارش', 'verbose_name_plural': 'گزارش ها'},
        ),
        migrations.AddField(
            model_name='reportadvertisment',
            name='status',
            field=models.CharField(choices=[('0', 'درحال بررسی'), ('1', 'تایید شده'), ('2', 'رد شده')], default=0, max_length=220, verbose_name='وضعیت'),
        ),
    ]
