# Generated by Django 5.1.5 on 2025-02-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0019_alter_reportadvertisment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportadvertisment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/report', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reportadvertisment',
            name='status',
            field=models.CharField(choices=[('0', 'درحال بررسی'), ('1', 'تایید شده'), ('2', 'رد شده')], default='0', max_length=220, verbose_name='وضعیت'),
        ),
    ]
