# Generated by Django 5.1.5 on 2025-02-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_module', '0020_reportadvertisment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportadvertisment',
            name='image',
            field=models.ImageField(blank=True, help_text='در صورت وجود عکس آپلود کنید در غیر این صورت نادیده بگیرید', null=True, upload_to='images/report', verbose_name='عکس'),
        ),
    ]
