# Generated by Django 5.1.5 on 2025-02-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_jobseeker_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='verified_by_admin',
            field=models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین'),
        ),
    ]
