# Generated by Django 5.1.5 on 2025-02-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_employer_verified_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعاتی درمورد شرکت'),
        ),
    ]
