# Generated by Django 5.1.5 on 2025-02-23 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_employer_description'),
        ('jobAndCompanyActivity_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expire_date_code',
            field=models.TimeField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobAndCompanyActivity_module.job', verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='کدفعالسازی'),
        ),
    ]
