# Generated by Django 5.1.5 on 2025-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_user_expire_date_code_alter_jobseeker_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expire_date_code',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا کد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='کد تایید'),
        ),
    ]
