# Generated by Django 5.1.5 on 2025-02-24 12:55

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_alter_user_expire_date_code_alter_user_verify_code'),
        ('home_module', '000X_add_tehran_districts'),
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='county',
            field=iranian_cities.fields.CountyField(default='', on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.county', verbose_name='نام شهرستان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_module.tehrandistrict', verbose_name='نام منطقه'),
        ),
        migrations.AddField(
            model_name='employer',
            name='province',
            field=iranian_cities.fields.ProvinceField(default='', on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province', verbose_name='نام استان'),
            preserve_default=False,
        ),
    ]
