# Generated by Django 5.1.5 on 2025-03-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobAndCompanyActivity_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=220, verbose_name='نام مکان')),
                ('job', models.CharField(max_length=220, verbose_name='شغل شما')),
                ('duration', models.CharField(help_text='براساس ماه', max_length=120, verbose_name='مدت زمان')),
            ],
        ),
    ]
