# Generated by Django 5.1.5 on 2025-03-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobAndCompanyActivity_module', '0002_insurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
